\input texinfo                  @c -*-texinfo-*-
@c %**start of header
@setfilename jiveaudio.info
@include version.texi
@settitle JiveAudio @value{VERSION}
@c %**end of header

@copying
This manual is for JiveAudio @value{VERSION}.

Copyright @copyright{} 2003-2008 Hypercore Software Design, Ltd.

@quotation
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
@end quotation
@end copying

@dircategory Gecko plugins
@direntry
* JiveAudio: (jiveaudio).       Multimedia plugin for Mozilla.
@end direntry

@titlepage
@title Using JiveAudio
@subtitle for version @value{VERSION}
@author Kaz Sasayama

@page
@vskip 0pt plus 1filll

@insertcopying
@end titlepage

@contents

@ifnottex
@node Top, Copying, (dir), (dir)
@top Using JiveAudio

@insertcopying
@end ifnottex

@menu
* Copying::                     
* Getting Started::             
* Using JiveAudio::             

@detailmenu
 --- The Detailed Node Listing ---

Getting Started with JiveAudio

* XPInstall::                   
* Manual Installation::         

Using JiveAudio in Your Web Page

* Embedding::                   
* Scripting::                   

@end detailmenu
@end menu

@node Copying, Getting Started, Top, Top
@unnumbered GNU General Public License

@include gpl-3.0.texi

@node Getting Started, Using JiveAudio, Copying, Top
@chapter Getting Started with JiveAudio

@iftex
JiveAudio is a multimedia plugin for WWW browsers based on Netscape
Gecko.
@end iftex

This chapter describes how to install JiveAudio into your browser.

@menu
* XPInstall::                   
* Manual Installation::         
@end menu

@node XPInstall, Manual Installation, Getting Started, Getting Started
@section XPInstall

@node Manual Installation,  , XPInstall, Getting Started
@section Manual Installation

@node Using JiveAudio,  , Getting Started, Top
@chapter Using JiveAudio in Your Web Page

@menu
* Embedding::                   
* Scripting::                   
@end menu

@node Embedding, Scripting, Using JiveAudio, Using JiveAudio
@section Embedding Media Objects

@node Scripting,  , Embedding, Using JiveAudio
@section Scripting JiveAudio

@bye
